codecov:
  bot:
    username: 'codecov'
    email: 'bot@codecov.io'

  notify:
    require_ci_to_pass: yes
    after_n_builds: 2
    notifications:
      - type: email
        recipients:
          - kalemaaaaaaaa@gmail.com
        subject: '{{status}} - {{commit}} - {{project_name}}'
        branch: main
        threshold: 1%
        when:
          success: always
          failure: always
          error: always

coverage:
  precision: 2
  round: down
  range: '70...100'
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment:
  layout: 'reach, diff, flags, files, footer'
  behavior: default

github_checks:
  annotations:
    branches:
      - main
    paths:
      - 'src/*.py'
    require_changes: true
