LEARNING_RATE_1: 0.01
LEARNING_RATE_2: 0.05
LEARNING_RATE_3: 0.05
LEARNING_RATE_4: 0.05
LEARNING_RATE_5: 0.05
NUMBER_OF_CLASSES: 2
EPOCHS_1: 5
EPOCHS_2: 5
EPOCHS_3: 5
EPOCHS_4: 5
EPOCHS_5: 5
BATCH_SIZE_1: 4
BATCH_SIZE_2: 64
