artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_source_URL: https://drive.google.com/file/d/15stuLDZkXNOgBUC1rnx5yXYdVPViUjNB/view?usp=sharing
  test_source_URL: https://drive.google.com/file/d/1mjmYzMdnn_UwSEgTQ7i-cJ5WSOokt9Er/view?usp=sharing
  train_data_file: artifacts/data_ingestion/train_data.zip
  test_data_file: artifacts/data_ingestion/test_data.zip
  unzip_dir: artifacts/data_ingestion

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
